sudo: required

services:
  - docker

before_install:
  - docker build -t "$DOCKER_ID"/react-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run "$DOCKER_ID"/react-client-test npm test -- --coverage

after_success:
  # Build images
  - docker build -t "$DOCKER_ID"/complex-client ./client
  - docker build -t "$DOCKER_ID"/complex-nginx -f ./nginx/Dockerfile.dev ./nginx
  - docker build -t "$DOCKER_ID"/complex-server ./server
  - docker build -t "$DOCKER_ID"/complex-worker ./worker
  # Login into docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push "$DOCKER_ID"/complex-client
  - docker push "$DOCKER_ID"/complex-nginx
  - docker push "$DOCKER_ID"/complex-server
  - docker push "$DOCKER_ID"/complex-worker